apiVersion: v1
kind: Service
metadata:
  name: employee-consumer
  labels:
    app: employee-consumer
  namespace: md
spec:
  type: NodePort
  ports:
  - port: 8091
    targetPort: 8091
    name: http
    protocol: TCP
  selector:
    app: employee-consumer