apiVersion: v1
kind: Service
metadata:
  name: employee-eureka-server
  labels:
    app: employee-eureka-server
  namespace: md
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    name: http
    protocol: TCP
  selector:
    app: employee-eureka-server